### PR TITLE
Sidkiq 3 support

### PR DESCRIPTION
**Pull request by kjg**

### CODE REVIEW

**Comment by bwthomas** [comment]
/home/travis/.rvm/gems/ruby-1.9.3-p551/gems/sidekiq-3.3.3/lib/sidekiq.rb:3:in `<top (required)>': Sidekiq 3.3.3 does not support Ruby 1.9. (RuntimeError)

... I think the thing to do is to remove ruby 1.9 from the travis.yml, update the README & then I'll release this as 0.1.0. Thoughts?

**Comment by kjg** [comment]
That works. The other option is to use multiple Gemfiles and test against sidekiq < 3.3.x on ruby 1.9 and >= 3.3.x on ruby 2.x.

Up to you which route we go, either way I'd be willing to do the work.

**Comment by bwthomas** [comment]
Yeah, I'm content to use versioning to solve this problem, keep it simple for a simple gem. Ping me when you've updated the pull request.

Thanks again :+1:

**Comment by kjg** [comment]
What do you mean by versioning? The multiple Gemfiles?

**Comment by bwthomas** [comment]
Sorry for the lack of clarity & delay. I meant to restrict pre 0.1.0 to sidekiq 2.x and 0.1.0 & beyond to 3.x & above.

So then the action item would be to just update the gemspec & the version in your pull request, & then I'll release two new versions. a 0.0.9 (or whatever) that's restricted to older sidekiq, and the result of your pull request as 0.1.0.

**Comment by kjg** [comment]
This is now passing by using multiple gemfiles to test against different versions of sidekiq using different ruby versions

**Pull request merged**
